/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dml.majiang.simulator.base.ui;

import dml.majiang.simulator.base.controller.Controller;
import dml.majiang.simulator.base.entity.PlayConfig;
import dml.majiang.simulator.base.entity.PlayStateEnum;

/**
 * @author DELL
 */
public class CommandPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommandPanel
     */
    public CommandPanel() {
        initComponents();
        Controller.setCommandPanel(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        modifyShoupaiCheckBox = new javax.swing.JCheckBox();
        modifyDoneButton = new javax.swing.JButton();
        setMopaiCheckBox = new javax.swing.JCheckBox();

        startButton.setText("开始");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        add(startButton);

        modifyShoupaiCheckBox.setText("修改初始手牌");
        modifyShoupaiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyShoupaiCheckBoxActionPerformed(evt);
            }
        });
        add(modifyShoupaiCheckBox);

        modifyDoneButton.setText("完成修改");
        modifyDoneButton.setEnabled(false);
        modifyDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyDoneButtonActionPerformed(evt);
            }
        });
        add(modifyDoneButton);

        setMopaiCheckBox.setText("指定摸牌");
        setMopaiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMopaiCheckBoxActionPerformed(evt);
            }
        });
        add(setMopaiCheckBox);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        Controller.startPan();
    }//GEN-LAST:event_startButtonActionPerformed

    private void modifyDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyDoneButtonActionPerformed
        Controller.modifyShoupaiDone();
    }//GEN-LAST:event_modifyDoneButtonActionPerformed

    private void modifyShoupaiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyShoupaiCheckBoxActionPerformed
        Controller.setCanModifyShoupai(modifyShoupaiCheckBox.isSelected());
    }//GEN-LAST:event_modifyShoupaiCheckBoxActionPerformed

    private void setMopaiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMopaiCheckBoxActionPerformed
        Controller.setCanSetMopai(setMopaiCheckBox.isSelected());
    }//GEN-LAST:event_setMopaiCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton modifyDoneButton;
    private javax.swing.JCheckBox modifyShoupaiCheckBox;
    private javax.swing.JCheckBox setMopaiCheckBox;
    private javax.swing.JButton startButton;

    // End of variables declaration//GEN-END:variables

    public void updateModifyShoupaiDoneButton(PlayConfig playConfig, PlayStateEnum playState) {
        if (playState.equals(PlayStateEnum.shoupaiEditing)) {
            modifyDoneButton.setEnabled(true);
        } else {
            modifyDoneButton.setEnabled(false);
        }
        revalidate();
        repaint();
    }
}
