/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dml.majiang.simulator.base.ui;

import javax.swing.*;
import java.util.List;

/**
 * @author DELL
 */
public class SpecialRuleStatePanel extends javax.swing.JPanel {

    /**
     * Creates new form SpecialRuleStatePanel
     */
    public SpecialRuleStatePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void showSpecialRuleState(List<String[]> panSpecialRulesStateView) {
        if (panSpecialRulesStateView == null || panSpecialRulesStateView.isEmpty()) {
            return;
        }
        removeAll();
        for (String[] specialRuleState : panSpecialRulesStateView) {
            add(new JLabel(specialRuleState[0] + ": " + specialRuleState[1]));
        }
        revalidate();
        repaint();
    }
}
